version: '2.3'

services:
  service1:
    build:
      context: ./ms-test-prometheus
      dockerfile: Dockerfile
    environment:
      APP_LOGGING_NAME: service_1
      APP_LOGGING_HOST: logstash
      APP_LOGGING_PORT: 5000
      APP_LOGGING_QUEUE_SIZE: 512
    container_name: service1
    hostname: service1
    restart: always
    ports:
      - "8801:8801"
    volumes:
      - ./docker/service1/logs:/tmp/logs