version: '2.3'

services:
  dept-service:
    build:
      context: ./ms-department-service
      dockerfile: Dockerfile
    environment:
      APP_LOGGING_NAME: deptService
      APP_LOGGING_HOST: logstash
      APP_LOGGING_PORT: 5000
      APP_LOGGING_QUEUE_SIZE: 512
    container_name: dept-service
    hostname: dept-service
    restart: always
    ports:
      - "8801:8801"
    volumes:
      - ./docker/dept-service/logs:/tmp/logs