# Server config
server:
  port: 8803


# Spring conf
spring:
  application:
    name: report-service

  # Default is no registration with Eureka a service registration server
  cloud:
#    service-registry:
#      auto-registration:
#        enabled: false
#        register-management: off
    loadbalancer:
      ribbon:
        enabled: true    # RibbonLoadBalancerClient deprecated. This setting uses BlockingLoadBalancerClient

# Actuator params
management:
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

resilience4j.circuitbreaker:
  instances:
    processService:
      slidingWindowSize: 50
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 20
      waitDurationInOpenState: 50s
      failureRateThreshold: 50

eureka:
  client:
    serviceUrl:
      defaultZone: ${app.eureka.server}