# Server config
server:
  port: 8801

# Spring conf
spring:
  datasource:
    url: jdbc:h2:mem:DBdepts;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop

# Actuator params
management:
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
